version: "3.9"
services:
  app:
    build: .
    container_name: movie_ticket
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - db
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
