version: "3.8"
services:
  app:
    build: .
    container_name: movie_ticket
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - db
    env_file:
      - .env
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis_server
    ports:
      - "6380:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5433:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-movie_ticket}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}

volumes:
  redis_data:
  postgres_data: